import React, { useState } from "react";
import TopBar from "./components/TopBar";
import Navbar from "./components/Navbar";
import Hero from "./components/Hero";
import PremiumCards from "./components/PremiumCards";
import About from "./components/About";
import Features from "./components/Features";
import Rules from "./components/Rules";
import Staff from "./components/Staff";
import CTA from "./components/CTA";
import Footer from "./components/Footer";
import { motion, AnimatePresence } from "motion/react";

// Import the high-quality assets generated by AI Studio
import heroBg from "./assets/images/revordian_hero_bg_1783563435101.jpg";
import logoUrl from "./assets/images/revordian_logo_1783563446542.jpg";

export default function App() {
  const [currentPage, setCurrentPage] = useState("home");

  const renderActivePage = () => {
    switch (currentPage) {
      case "home":
        return (
          <motion.div
            key="home-page"
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -15 }}
            transition={{ duration: 0.3 }}
            className="flex flex-col w-full"
          >
            {/* Immersive Hero / Game Cinematic Section */}
            <Hero logoUrl={logoUrl} bgUrl={heroBg} onPageChange={setCurrentPage} />

            {/* Server Premium Information and Interactive Status Cards */}
            <PremiumCards />

            {/* Direct Conversion Join CTA Section */}
            <CTA onPageChange={setCurrentPage} />
          </motion.div>
        );

      case "fitur":
        return (
          <motion.div
            key="fitur-page"
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -15 }}
            transition={{ duration: 0.3 }}
            className="w-full flex-grow"
          >
            {/* Customized Interactive Server Features & Mechanics */}
            <Features />
            <CTA onPageChange={setCurrentPage} />
          </motion.div>
        );

      case "roleplay":
        return (
          <motion.div
            key="roleplay-page"
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -15 }}
            transition={{ duration: 0.3 }}
            className="w-full flex-grow"
          >
            {/* Detailed Dual World Explanation (About Section) */}
            <About />
            <CTA onPageChange={setCurrentPage} />
          </motion.div>
        );

      case "rules":
        return (
          <motion.div
            key="rules-page"
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -15 }}
            transition={{ duration: 0.3 }}
            className="w-full flex-grow"
          >
            {/* Modern Interactive Rules Timeline & Zero Tolerance Warning Card */}
            <Rules />
            <CTA onPageChange={setCurrentPage} />
          </motion.div>
        );

      case "admin":
        return (
          <motion.div
            key="admin-page"
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -15 }}
            transition={{ duration: 0.3 }}
            className="w-full flex-grow"
          >
            {/* Minecraft Avatar Staff Directory Card Grid */}
            <Staff />
            <CTA onPageChange={setCurrentPage} />
          </motion.div>
        );

      case "support":
        return (
          <motion.div
            key="support-page"
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -15 }}
            transition={{ duration: 0.3 }}
            className="w-full flex-grow text-center"
          >
            {/* Dedicated Support Center CTA view */}
            <div className="py-12">
              <div className="max-w-4xl mx-auto mb-12 px-4">
                <span className="text-xs uppercase font-mono tracking-widest text-[#31C5FF] bg-[#31C5FF]/10 px-3 py-1 rounded-full border border-[#31C5FF]/20">
                  Support Center
                </span>
                <h2 className="text-3xl sm:text-4xl font-sans font-black text-white mt-4 tracking-tight">
                  BUTUH BANTUAN DI SERVER?
                </h2>
                <p className="text-gray-400 mt-2 text-sm sm:text-base max-w-xl mx-auto">
                  Kami selalu siap membantu Anda. Silakan hubungi tim Admin kami melalui platform sosial Media atau tanyakan langsung di server.
                </p>
              </div>
              <CTA onPageChange={setCurrentPage} />
            </div>
          </motion.div>
        );

      default:
        return null;
    }
  };

  return (
    <div className="min-h-screen bg-[#090A12] text-gray-100 flex flex-col font-sans selection:bg-[#6E3BFF]/30 selection:text-[#31C5FF] scroll-smooth">
      {/* Dynamic Sticky/Fixed Combined Header Container */}
      <header className="fixed top-0 left-0 right-0 z-50 flex flex-col shadow-2xl">
        {/* 1. Top Announcement/Developer Bar */}
        <TopBar />

        {/* 2. Main Navigation Menu */}
        <Navbar logoUrl={logoUrl} currentPage={currentPage} onPageChange={setCurrentPage} />
      </header>

      {/* Main Container sitting cleanly below the fixed header */}
      <main className="flex-grow pt-[72px] sm:pt-[116px] flex flex-col w-full">
        <AnimatePresence mode="wait">
          {renderActivePage()}
        </AnimatePresence>
      </main>

      {/* 10. Multi-column Double Footer with dynamic Developer data */}
      <Footer logoUrl={logoUrl} onPageChange={setCurrentPage} />
    </div>
  );
}
